### ISSUE TITLE
Optimalizace kontroly verze

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono-be#23]
Momentálně se kontroluje neefektivně při každém dotazu do DB.

Is part of: Loono-cz/loono-tasks#51

**Comment by cecan12** [comment]
Kontrola dokonce neni logicky spravne, protoze se kontroluji postupne verze major, minor, patch. Tzn. pokud bude api na verzi 1.2.3 a aplikace na 1.3.1, tak spolu nebudou fungovat, byt dle https://semver.org/lang/cs/ by to melo byt ok.

**Comment by cecan12** [comment]
nakonec zachovana logika viz diskuse na slacku, ale optimalizovat kod pro kontrolu
