### ISSUE TITLE
Vlastní prohlídky - číselníky - BE

### ISSUE THREAD

**Issue by janblahacgi** [Loono-cz/loono-be#36]
typ prohlídky viz komentar od Deli 

[specialista](https://docs.google.com/spreadsheets/d/1mzABhp0fzzCAjIXmfzfDnVkYYUYKsSH5BMuKSefo1Vs/edit#gid=0) dostupny zde (jen to, co je soucasti Preventivky 2.0)

**Comment by Deli-Sedlackova** [comment]
Typ prohlídky: 
Vyšetření
Kontrola
Odběry
Zobrazovací metody

**Comment by janblahacgi** [comment]
Chybí: mamograf, kolonoskopie, dermatologie, očař (ofta)

**Comment by Deli-Sedlackova** [comment]
V číselníku v app chybí Zobrazovací metodody

**Comment by StepanDrozdek** [comment]
Nechybí, bylo pouze v rámci apk špatně přeloženo a je již opraveno
